### ISSUE TITLE
Translation to Spanish Latinamerican

### ISSUE THREAD

**Issue by PONCE54958** [SparkDev97/SnowBoardLocalisation#11]
[es.lproj.zip](https://github.com/SparkDev97/SnowBoardLocalisation/files/3826578/es.lproj.zip)

my twitter @PONCE54958

**Comment by SparkDev97** [comment]
Have added this in as es-419.lproj for Spanish (Latin American) (as per: https://en.wikipedia.org/wiki/Language_code)
